### ISSUE TITLE
Can't choice sample rate

### ISSUE THREAD

**Issue by emviveros** [manuel-rhdt/snd-microbookii#2]
Hello!
 I'm able to compile and run snd-microbookii module in manjaro linux. So now, using cadence, doesn't possible to change sample rate at jack initialization. It sets SR at 96kHz and it is.

Something I can do?

**Comment by emviveros** [comment]
In Debian stretch the 96kHz sample rate persistent issue are present to.

**Comment by manuel-rhdt** [comment]
Sorry for late response. Without changing the driver, changing of sample rate is not possible. Maybe at some point I will look into this. I am happy to accept a pull request that changes the driver accordingly.
