### ISSUE TITLE
Any chance this can be made to work with the microbook I

### ISSUE THREAD

**Issue by teknopaul** [manuel-rhdt/snd-microbookii#5]
I have a microbook 1 wondering if this can be modified to work with that?  Currently it fails to probe the device.

```
[  399.325395] usb 1-2: new full-speed USB device number 9 using xhci_hcd
[  399.481984] usb 1-2: New USB device found, idVendor=07fd, idProduct=0004
[  399.481990] usb 1-2: New USB device strings: Mfr=1, Product=2, SerialNumber=0
[  399.481994] usb 1-2: Product: MicroBook
[  399.481998] usb 1-2: Manufacturer: MOTU
[  399.484219] usb 1-2: snd-microbookii: error during probing
[  399.484233] snd-microbookii: probe of 1-2:1.0 failed with error -71
```

**Comment by manuel-rhdt** [comment]
I am sorry but you have the first version of the Microbook. It is literally impossible to develop a device driver without having access to the device. I do not own a Microbook 1. 

So I‘m afraid there is no way I can help you here. 

On the off chance that someone wants to try kernel development and have the older device they certainly are invited to contribute.

**Comment by teknopaul** [comment]
I have the device in front of me. I've never done any serious kernel dev other than fixing a driver for kernel changes.
Not sure where to start, wondering how you got started on this driver? how do you find out the protocol the device speaks?

the device I have identifies as :0004 as well
USB_DEVICE(0x07FD, 0x0004)
but does not support 96k

**Comment by manuel-rhdt** [comment]
Well, depending on your experience with C programming and kernel programming in general this can be quite a long journey. 

# Kernel development

If you have never written a simple kernel module from scratch I would suggest to start there (there are various tutorials available online). After that you at least have basic understanding of how the build process works and how the kernel API is roughly structured.

To actually write an audio driver though you have to familiarize yourself with the concepts and APIs of Alsa. A good resource (although not always applicable to usb audio interfaces) is 
https://www.kernel.org/doc/html/v4.17/sound/kernel-api/writing-an-alsa-driver.html . If you have understood the general structure of an audio driver your best bet is to look at my code and the other usb audio drivers in the kernel tree and try to understand what is going on.

# Protocol reverse engineering

One of the more difficult parts is actually finding out the protocol that the microbook understands. To do that I used USBPcap with Wireshark on a windows computer to capture the USB traffic whenever the device was plugged in. After some time you start to notice patterns. Hopefully the communication protocol of the Microbook I is similar to the Microbook 2 and you may be able to reuse most of the code from snd-microbookii. You can also use virtualbox and wireshark on the linux host to capture the usb packets but I never got audio capture/playback to work over virtualbox.

A short but useful resource is 
https://kicherer.org/joomla/index.php/en/blog/38-reverse-engineering-a-usb-sound-card-with-midi-interface-for-linux

I hope this helps. I know it is not easy but before writing this driver I actually never had really written kernel code. Once the device works it is very rewarding.

**Comment by teknopaul** [comment]
Ok cheers, I started to look at usbpcap i've played about with alsa a bit written midi drivers for windows to linux over ethernet and done the basics of kernel dev before. If i get the basics working I'll see if I can make the changes as patches to your microbookii driver. These boxes have a lot in common. might be cool to port the control surface to Linux. The microbook 1 one has eqs, compressors and sound routing that looks interesting. Might be able to extract some common code there. Presumably control instructions are relativly simple to reverse.

**Comment by teknopaul** [comment]
Hi Manuel , I've made a bit of progress.  I have usbpcap working copied the boot sequence from the microbook I from Windows.  The first microbook seems to be 16bit 441000 and usb messages are a bit different.
There are a few magic numbers in the code I've had to fiddle.  

One particular 6 I've had to change to a 4 I'm calling the magic factor :)  , presumably this is 2 * bytes_per_packet 16 - 24bit

out_packet->packet_size[i] =
				usb_urb->iso_frame_desc[i].actual_length / MAGIC_FACTOR
				* 8;

sync_stream->max_packet_size =
			MAGIC_FACTOR * max_frames_per_packet * bytes_per_frame;

Can you explain this magic 6?  I guess it not important if it works.

Both I and II seem to have the same USB identifier 07fd:0004 Mark of the Unicorn 

In order to make the driver detect the version I will have to find some difference in the info provided over USB when it connects.  can you send the output from 

lsusb -v -s 001:011  (or what ever device id its assigned)

for your device.

I've managed to record some white noise from my device so progress,  I think I still have a long way to go.  Any chance I could submit what I have to a branch in this project?

thanks again for tips and encouragement.
